import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "LockBox",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.ico", // Указываем путь к favicon
    },
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <head>
            <meta charSet="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>LockBox</title>
            {/* Если нужно, добавьте дополнительные теги или метаданные */}
        </head>
        <body>{children}</body>
        </html>
    );
}
