services:
  postgres:
    container_name: lockbox-postgres
    image: postgres:15-alpine
    ports:
      - '6969:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lock_box
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z
    restart: unless-stopped
    networks:
      - lockbox-net

  backend:
    container_name: lockbox-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      SERVER_PORT: 0.0.0.0:5000
      STORAGE_LIMIT: 20
      BODY_LIMIT_MB: 20
      JWT_SECRET: 82026ea3dfe8af4dbefc8db9495e442870b4408415d2ced47ab8d50b97dd9da203bfae35e9df9f527de3ae117d3af950cc57ae77967aacc9039130b86895a4ae
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/lock_box?sslmode=disable
      MINIO_ENDPOINT: minio:9090
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: uploads
      LOG_LEVEL: debug
      BACK_LOG_FILE: ${BACK_LOG_FILE}
      FIBER_LIMIT_REQ: 100
    volumes:
      - ./data/logs/backend:/app/logs/:z
    depends_on:
      - postgres
      - minio
    restart: unless-stopped
    command: sh -c "./backend"
    networks:
      - lockbox-net

  frontend:
    container_name: lockbox-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:z        
      - node_modules:/app/node_modules  
      - next_cache:/app/.next:z  
    environment:
      NEXT_PUBLIC_SERVER: http://lockbox-backend:5000
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
      NODE_ENV: development
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - lockbox-net

  minio:
    container_name: lockbox-minio
    image: minio/minio:latest
    ports:
      - '9090:9090'
      - '9091:9091'
    volumes:
      - ./data/minio:/data:z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --address ":9090" --console-address ":9091"
    restart: always
    networks:
      - lockbox-net

volumes:
  pgdata:
    name: lockbox-pg-data
  miniodata:
    name: lockbox-minio-data
  node_modules:
  next_cache:
    
networks:
  lockbox-net:
    name: lockbox-net
    driver: bridge
