basePath: /api
definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  models.FileUpload:
    properties:
      filename:
        type: string
      message:
        type: string
    type: object
  models.ListFile:
    properties:
      files:
        items:
          type: string
        type: array
      storage:
        $ref: '#/definitions/models.ListFileUsed'
    type: object
  models.ListFileUsed:
    properties:
      limit:
        type: integer
      used:
        type: integer
    type: object
  models.LoginDTO:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.LoginMessage:
    properties:
      message:
        type: string
      token:
        type: string
      user:
        $ref: '#/definitions/models.MessageDTO'
    type: object
  models.MessageDTO:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
  models.Profile:
    properties:
      storage:
        $ref: '#/definitions/models.ProfileStorage'
      user:
        $ref: '#/definitions/models.ProfileUser'
    type: object
  models.ProfileStorage:
    properties:
      limit:
        type: integer
      used:
        type: integer
    type: object
  models.ProfileUser:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.RegisterDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  models.RegisterMessage:
    properties:
      message:
        type: string
      user:
        $ref: '#/definitions/models.MessageDTO'
    type: object
  models.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  models.UpdateStorage:
    properties:
      new_limit:
        type: integer
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      is_admin:
        type: boolean
      name:
        type: string
      storage_limit:
        type: integer
    type: object
host: localhost:5000
info:
  contact: {}
  description: This is the API documentation for LockBox SaaS app.
  title: LockBox API
  version: 0.1.1
paths:
  /admin/make_admin/{user_id}:
    put:
      description: Gives a user admin privileges
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Grant admin rights
      tags:
      - admin
  /admin/revoke_admin/{user_id}:
    put:
      description: Removes admin privileges from a user
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Revoke admin rights
      tags:
      - admin
  /admin/update_limit:
    put:
      consumes:
      - application/json
      description: Sets a new storage limit for a specific user
      parameters:
      - description: Storage limit info
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UpdateStorage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update user storage limit
      tags:
      - admin
  /admin/users:
    get:
      description: Returns a list of all registered users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get all users
      tags:
      - admin
  /delete/{filename}:
    delete:
      description: Deletes a specific file belonging to the authenticated user
      parameters:
      - description: File name
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a file
      tags:
      - file
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: User login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/models.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Log in user
      tags:
      - auth
  /logout:
    post:
      description: Logout by removing token on the client side
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
      summary: Log out user
      tags:
      - auth
  /profile:
    get:
      consumes:
      - application/json
      description: Returns the current user's profile and storage usage info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Profile'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - profile
  /register:
    post:
      consumes:
      - application/json
      description: Create an account with email and password
      parameters:
      - description: User registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.RegisterDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.RegisterMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Register a new user
      tags:
      - auth
  /storage:
    get:
      description: Returns a list of filenames and storage info for the authenticated
        user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ListFile'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List user's files
      tags:
      - file
  /storage/{filename}:
    get:
      description: Downloads a specific file for the authenticated user
      parameters:
      - description: File name
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Download a file
      tags:
      - file
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file for the authenticated user
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FileUpload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Upload a file
      tags:
      - file
schemes:
- http
swagger: "2.0"
